version: '3.8'

services:
  mysql:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD:rcg2022
